#######################################################
ARG BUILDER_IMAGE=thundermoon:builder


#########################################################
# docker build -t thundermoon:releaser --target=releaser -f .semaphore/Dockerfile_release .
FROM $BUILDER_IMAGE as releaser

WORKDIR /app/apps/thundermoon_web/
RUN mix phx.digest

WORKDIR /app
COPY config/ /app/config

RUN mix compile
RUN mix release

#########################################################
# docker build -t thundermoon:app --target=app -f .semaphore/Dockerfile_release .
FROM alpine:3.12 as app

RUN apk add --update bash openssl

WORKDIR /app

COPY --from=releaser /app/_build/prod/rel/thundermoon_umbrella /app
COPY *.sh /app/

ENV HOME=/app

CMD ["/app/run.sh"]
